### ISSUE TITLE
locking some values

### ISSUE THREAD

**Issue by mirlip** [s-leger/archipack#15]
I don't know how hard it is to have a good constraint solver in python, but a way to be able to lock some  values would be great. At the moment, if you modify the length of one wall, it will extend or shrink the next segment automatically. sometime, you want a room to have a fixed length. In this case, it would help to have a little lock near the value to keep a wall constant, whatever happens to the other ones.

**Comment by s-leger** [comment]
Agree, having all segments affected by size is an issue.
Solving constraints not realy an issue, segments allready are. 
If we are able to lock segment, simply apply transform along wall until a locked one is found. 
To do so we must be able to lock rotation and length.

At this time, in order to resize a segment keeping other unaffected, you have the "drag-snap" manipulator square handle right on wall edges. While manipulating you're able to either snap and/or constraint axis with keyboard xy and set size via keyboard too.

**Comment by s-leger** [comment]
Added ability to select multiple drag manipulators - square handles on wall edges.
Drag to select by area, then use one of selected handle (blue) to modify all.
Allow precise manipulation of multiple wall segments at once.

**Comment by mirlip** [comment]
the handles are great. A solution for the angles to also slide along the next wall instead of rotating the whole room would help a lot.

**Comment by mirlip** [comment]
just saw this slide mode is already marked as enhancement in another issue, sorry to make a double.

**Comment by s-leger** [comment]
no problem,
this point out a real need for such ability

**Comment by s-leger** [comment]
Upcomming 1.4 does implement bi-directional manipulators for size and angle, with more user friendly behaviour no more updating the whole shape of objects, but only manipulated segment and neighboors.

**Comment by mirlip** [comment]
pure awesomeness

**Comment by mirlip** [comment]
is it in some branches here?

**Comment by s-leger** [comment]
Require some more testings/polishing, also still not supporting curved segs. 
Will push soon in 1.4_dev
see [1.4 video preview](https://www.youtube.com/watch?v=hTjCMk_Qzak)

**Comment by mirlip** [comment]
oh my. And the slabs all update in real time :o

**Comment by s-leger** [comment]
Implemented in 2.0 manipulators, there is a even SPACE shortcut to lock manipulators so changes
