### ISSUE TITLE
Can I keep the manipulator from disappearing by right-clicking?

### ISSUE THREAD

**Issue by kksbluesky** [s-leger/archipack#151]
I'm sorry for the automatic Japanese translation.

Archipack version:
1.2.83
Blender version:
2.8
Os version:
windows10

Description of the issue:
I set the blender 3D view's viewpoint rotation to right click, but when I rotate the view, the Archipack manipulator disappears.
Please let me know if there is a way to keep the manipulator right-click.

**Comment by s-leger** [comment]
Hi,
There is currently no other way than editing code to override the right click exit.
In order to reactivate select your object, in the right panel of 3d view you'll find "Manipluate" button (small hand) on top of the Archipack tab.
You may setup a shortcut eg (alt+m) to archipack.manipulate operator (Preferences -> Keymap -> 3d view -> object mode -> object mode (global) ).

**Comment by kksbluesky** [comment]
Thank you for your reply.
It seems that it is impossible with the current specifications.
It seems difficult to edit the code, so I will set a shortcut.
