### ISSUE TITLE
Unable to use Draw Tool for Walls

### ISSUE THREAD

**Issue by OkamuraYasuyuki** [s-leger/archipack#174]
Archipack version: 1.2.83

Blender version:2.82

Os version: Windows 10

Description of the issue: After selecting the draw wall option next to wall, a blue UI bar appears toward the bottom of the screen that disappears as soon as the mouse is moved. The ability to draw walls also disappears. Essentially, after selecting the draw option and interacting with the viewport, all I can do is box select as if no tool were engaged.

**Comment by s-leger** [comment]
Looks like an issue with your click/release cycle.
In order to draw wall, click and keep pressed, drag and then release to create the first segment.
Right click will cancel the draw tool, and selecting any other object too.

**Comment by damienmahoney** [comment]
This is still an issue. 

Archipack version: 1.2.83
Blender version:2.82a
OS: OpenSuse

It seems scenes can get corrupted and then don't work with the draw tool. A fresh scene works but once a scene changes in some way this issue can happen. I found sometimes deleting the 'Archipack_snap_helper' can resolve the issue but not always.

**Comment by damienmahoney** [comment]
I found a way around this. You can append the 'Archipack_snap_helper' from a working file.

**Comment by damienmahoney** [comment]
Archipack seems to have a problem if this 'Archipack_snap_helper' is moved from it's root location under objects.

**Comment by s-leger** [comment]
You should never disable / hide archipack's collections. 
Could be the source of the error.
Once a draw tool fails, it is removed from operators, so you have to restart blender in order to get it working again.

The snap helper is linked to main collection by default, and should be removed automatically by the snap tool once done (if sucessfull). It will work whatever the collection it belongs, as long as it is not hidden / disabled.

**Comment by damienmahoney** [comment]
That would probably be the the issue. I had the 'Archipack_snap_helper' under an empty and hidden. Once I deleted this original it worked again. The 'Archipack_snap_helper' is indeed deleted after each operation but when I tried to add a door and it failed just before the boolean operation the 'Archipack_snap_helper' was left in the scene. 
This may have been because I moved the walls up in z before adding doors?

Below was the error I got when adding the door
`
Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/archipack/archipack_door.py", line 1756, in modal
    bpy.ops.archipack.single_boolean()
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/archipack/archipack_autoboolean.py", line 573, in execute
    manager.singleboolean(context, wall, o)
  File "/usr/share/blender/2.82/scripts/addons/archipack/archipack_autoboolean.py", line 520, in singleboolean
    bpy.ops.archipack.parent_to_reference()
  File "/usr/share/blender/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.archipack.parent_to_reference.poll() failed, context is incorrect

location: /usr/share/blender/2.82/scripts/modules/bpy/ops.py:201



location: <unknown location>:-1
`
