### ISSUE TITLE
Roof with random tiling unavailable in Pro version.

### ISSUE THREAD

**Issue by RyanJMcGowan** [s-leger/archipack#179]
Archipack version: 2.0.9

Blender version: 2.9

Os version: Win 10 Pro

Description of the issue: Random roof tile materials are not created on Pro version, but is created in the free version.

Workaround: Create the Roof in pro. Enable the free plug in. Select the Roof, and change to Roman style. Disable the free plug in. Save the roof style in the Pro version.

**Comment by s-leger** [comment]
Hi Ryan,
Take a look at your e-mails (probably spam folder), you should find a link to download latest version from blender-archipack.org
Current version is 2.3.0

**Comment by RyanJMcGowan** [comment]
I have installed 2.3.0 and updated it on Blender. I disabled the free version and ArchiMesh. I started from a clean file and created a new roof. The roof comes in with a material containing 3 slots, one for the wood components, copper, and the tile. Is this the correct behavior? The other add-on came in with a material containing a dozen slots or so.

**Comment by s-leger** [comment]
In 2.x version, "randomness" of tiles is done through shader. This allow to simplify the material library and management.
If you go in "Shading" workspace / editor, and select the "Randoms xxx roof" material (tiles) you'll find a "Multiply" node, controlling the randomness amount.

**Comment by RyanJMcGowan** [comment]
I see. I neglected to append the material file from the plugin folder. Thank you for taking the time, and the great product.

**Comment by s-leger** [comment]
Ensure you setup archipack_2_matlib.blend  (link in e-mail)
It is not the same than 1.2x

**Comment by janmechtel** [comment]
I had trouble finding out how "randomized material" is done now (through shading) ...

... because i created a floor with Archipack 1.x and then upgraded to PRO 2.x I had to recreate the floor and then in worked with the shader.

I also kindly suggest to update this part of the documentation: https://blender-archipack.gitlab.io/user/archipack%20objects.html#id24 Where "floor components" still shows randomized material

Awesome product in all aspects! 😍
