### ISSUE TITLE
Sometimes auto-generated holes don't properly cut walls.

### ISSUE THREAD

**Issue by onceadrog** [s-leger/archipack#245]
Archipack version: 2.3.4

Blender version: 2.9.2

Os version: Win10 v2004 build 19041.928

Description of the issue:
In some cases, the hole generated for a door or window doesn't align properly to the wall it is meant to cut, requiring tweaking position of the hole, or spamming the Auto Boolean button in Archipack>Wall>UI Tabs.
![image](https://user-images.githubusercontent.com/6299372/116742696-5a126480-a9bd-11eb-90ea-be9607904d8c.png)

**Comment by s-leger** [comment]
This is a typical boolean issue, most of the time due to "coplanar" face between hole and wall. Boolean modifier use a random seed so it may sometimes work and sometimes fail from same exact initial situation.
It occurs when either 2 holes are exactly side by side, or a hole is exactly touching wall's edge.
In such situation, you must identify failing hole, and slightly move / alter size (0.01mm is enough) so it is no more exactly coplanar.
By the way, please use e-mail to support@blender-archipack.org for pro version support.
