### ISSUE TITLE
Wrong Boolean assignment with floors and assemblies

### ISSUE THREAD

**Issue by hoverkraft** [s-leger/archipack#404]
Archipack version: 2.8.0

Blender version: 4.1.0

Os version: Fedora 39

Description of the issue:

When instancing a floor to an assembly the boolean modifier of the instanced floor is set to "Object", not to the "Holes" Collection. Doors, Windows etc. do not get cut on the instance. Changing the modifier to the "Holes" collection fixes the issue.

**Comment by hoverkraft** [comment]
Don't know if this is relateed: the Autoboolean has a couple of union booleans and with "fast" they fail, once I set them on "exact" it works. The problem showed up when placing doors, only the last one would have a working boolean.

**Comment by s-leger** [comment]
In order to create instance of a level, select your reference point and use "duplicate" tool, it should take care of the boolean automatically.

Blender's boolean "Fast" solver allow real-time modifications (where exact one is painfully slow), but comes with some limitations.

- Holes must not cross or touch eachother, if they are too close, you should disable automatic hole in the opening object (window or door) and rely on handmade hole geometry or archipack hole object instead. 
- Hole faces must not be co-planar with any edge / vertex of wall.

If neither of this is avoidable, you may switch the solver to "exact" by hand.

Archipack rely on 2 boolean operations, first one "auto merge" actually create a single object from your holes, then autoboolean use the result of auto merge as hole to actually cut the wall, so it is more reliable.

You should rely on support by e-mail support@blender-archipack.org as it is the fastest way to communicate.

**Comment by hoverkraft** [comment]
Got it! I Thanks for the pointers. I ended up making Level Collections and instancing those works really well and super performant. Archipak saved me a ton of time, it's a great addon, thank you for your work.
