### ISSUE TITLE
Cannot make slide animation work on rail windows

### ISSUE THREAD

**Issue by scull2014** [s-leger/archipack#46]
Hi I cannot make the slide animation work on rail windows.I am not sure if I am doing something wrong as I can make the animation work fine on archimesh.
I am basically right clicking without releasing on a pane then moving which works fine on archimesh.

Hope you can help

Also thanks for such a great pluggin

**Comment by s-leger** [comment]
Hi,
Window panels translation are "locked", you may unlock "X" location in "N" panel, under Transform.
Should take a look at unlock X by default for rail windows panels - initialy set like this to only allow rotation on regular windows panels -.

**Comment by scull2014** [comment]
Ok thanks got it working and made it default by removing this line in plugin code for anyone else that needs this
C:\Program Files\Blender Foundation\blender\2.79\scripts\addons\archipack\archipack_window.py
line 2170
`        o.lock_location[0] = True`

**Comment by s-leger** [comment]
In order to support duplicates and linked you should also modify
line 1149:  p.lock_location[0] = self.window_type is not 'RAIL'

For rotations, i'm allowing x and z rotations by default as some windows may allow both.
You may use r + z or r + x to constraint rotation.

Have to handle this properly at panel creation time too, as you do, but taking into account the window type.

**Comment by s-leger** [comment]
Fixed in master, feel free to download from repo
