### ISSUE TITLE
Create our own model ?

### ISSUE THREAD

**Issue by metal3d** [s-leger/archipack#47]
Hi,
First, congrat for that addon that is very efficient and usefull.
I've got several problem to resolve, so I will open several issues (sorry) but the firs one is a question:

How can we create (and propose) other window or door model for example?

**Comment by s-leger** [comment]
Hi,
In order to make your own preset, modify parameters until you're happy with it. 
Then Use the + button beside "Window Presets" and set a meanfull name for your preset.
The system should compute a thumbnail pic (using a background instance of blender) and after 5-10 seconds you should be able to select it right from preset menu.

**Comment by metal3d** [comment]
Ok thanks. I will check that.

**Comment by s-leger** [comment]
Any contributions are welcome,  
feel free to share your presets, 
will be happy to add them.

**Comment by garyritchie** [comment]
Is it possible to create a new window type like this?...

![image](https://user-images.githubusercontent.com/853094/41123704-8b77d2a4-6a6d-11e8-96c9-9fa274d4cc95.png)

(double hung windows with/out mullions)

**Comment by s-leger** [comment]
Double hung support was added in archipack 2.0.1
Support for custom doors windows is available through custom objects.
